apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    webserver: nginx
    number: "1"
    type: assign
  annotations:
    build-date: 2018-06-01
spec:
  containers:
  # - image: xvrtnzy9456/k8s-homework-nginx:0.1
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html/
    # - mountPath: /var/www/html/secret
      name: account-secret
  volumes:
  - name: account-secret
    secret:
      secretName: account
      items:
        - key: username
          path: data.html
        - key: account
          path: data.html
