apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  labels:
    webserver: nginx
    number: "2"
    type: assign
  annotations:
    build-date: 2018-05-30
spec:
  containers:
  # - image: xvrtnzy9456/k8s-homework-nginx:0.1
  - image: nginx:latest
    # imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    volumeMounts:
    - mountPath: /usr/share/nginx/html
    # - mountPath: /var/www/html/config
      name: password-configmap
  volumes:
  - name: password-configmap
    configMap:
      name: password
      items:
        - key: password
          path: data.html


# ---

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: password
# data:
#   password: "12345678"