apiVersion: v1
kind: Service
metadata:
  labels:
    webserver: nginx
  name: nginx-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    webserver: nginx
    type: assign
  type: NodePort